### ISSUE TITLE
Where is the webinar repo?

### ISSUE THREAD

**Issue by dbolser** [UofABioinformaticsHub/RNAseq_snakemake#8]
The link to this repo contained here:
https://www.youtube.com/watch?v=9HxTURMP_Uc

don't exist.

Did that repo get moved or deleted?

**Comment by dbolser** [comment]
For example, in a few places he says 'see the files', which I can't. Also copies of the slides were promised to be there...

**Comment by nathanhaigh** [comment]
The repo was moved to https://github.com/nathanhaigh/2019_EMBL-ABR_Snakemake_webinar

The old link (https://github.com/UofABioinformaticsHub/2019_EMBL-ABR_Snakemake_webinar) should automatically redirect there if entered into an address bar.

Let me know over at https://github.com/nathanhaigh/2019_EMBL-ABR_Snakemake_webinar/issues if you still have issues.
